name: Build Docker Images

on: push

jobs:
  ansible-python2:
    name: "Ansible Python 2"
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: bionic
            ansible: 2.5.4
            ansible_git: v2.5.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ansible ${{ matrix.ansible }}
        uses: docker/build-push-action@v6
        with:
          target: ansible
          push: ${{ github.event_name != 'pull_request' }}
          file: python2/Dockerfile
          tags: |
            hnhs/ansible:py2-${{ matrix.distro }}-${{ matrix.ansible }}
            ghcr.io/hicknhack-software/ansible:py2-${{ matrix.distro }}-${{ matrix.ansible }}
            hnhs/ansible:py2-${{ matrix.distro }}-latest
            ghcr.io/hicknhack-software/ansible:py2-${{ matrix.distro }}-latest
          build-args: |
            DISTRO=${{ matrix.distro }}
            ANSIBLE_VERSION=${{ matrix.ansible }}
            ANSIBLE_GIT_BRANCH=${{ matrix.ansible_git }}

  ansible-python3:
    name: "Ansible Python 3"
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: focal
            ansible: 2.11.4
            ansible_git: v2.11.4
          - distro: noble
            ansible: 2.17.1
            ansible_git: v2.17.1
            extra_tags: |
              hnhs/ansible:latest
              hnhs/ansible:noble-latest
              ghcr.io/hicknhack-software/ansible:latest
              ghcr.io/hicknhack-software/ansible:noble-latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ansible ${{ matrix.ansible }}
        uses: docker/build-push-action@v6
        with:
          target: ansible
          push: ${{ github.event_name != 'pull_request' }}
          file: python3/Dockerfile
          tags: |
            hnhs/ansible:${{ matrix.distro }}-${{ matrix.ansible }}
            ghcr.io/hicknhack-software/ansible:${{ matrix.distro }}-${{ matrix.ansible }}
            ${{ matrix.extra_tags }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            ANSIBLE_VERSION=${{ matrix.ansible }}
            ANSIBLE_GIT_BRANCH=${{ matrix.ansible_git }}
